-- lua/cool_lightning/highlights.lua
-- All highlight group definitions for Cool Lightning

local M = {}

function M.setup(c)
  local highlights = {
    -- ── Base editor ──────────────────────────────────────────────────────
    Normal         = { fg = c.fg,       bg = c.bg },
    NormalFloat    = { fg = c.fg,       bg = c.bg_float },
    FloatBorder    = { fg = c.border_hl, bg = c.bg_float },
    NormalNC       = { fg = c.fg_dim,   bg = c.bg },
    Visual         = { bg = c.bg_sel },
    VisualNOS      = { bg = c.bg_sel },
    CursorLine     = { bg = c.bg_subtle },
    CursorLineNr   = { fg = c.keyword,  bold = true },
    LineNr         = { fg = c.fg_muted },
    SignColumn     = { fg = c.fg_muted, bg = c.bg },
    ColorColumn    = { bg = "#4a1515" },
    Folded         = { fg = c.fg_dim,   bg = c.bg_subtle },
    FoldColumn     = { fg = c.fg_muted },
    MatchParen     = { fg = c.modifier, bold = true, underline = true },
    Search         = { fg = c.bg,       bg = c.modifier },
    IncSearch      = { fg = c.bg,       bg = c.keyword },
    Substitute     = { fg = c.bg,       bg = c.red },
    StatusLine     = { fg = c.fg,       bg = c.bg_subtle2 },
    StatusLineNC   = { fg = c.fg_dim,   bg = c.bg_subtle },
    WinSeparator   = { fg = c.border },
    Pmenu          = { fg = c.fg,       bg = c.bg_float },
    PmenuSel       = { fg = c.fg,       bg = c.bg_sel, bold = true },
    PmenuSbar      = { bg = c.bg_subtle2 },
    PmenuThumb     = { bg = c.border },
    WildMenu       = { fg = c.bg,       bg = c.blue },
    ModeMsg        = { fg = c.green,    bold = true },
    MoreMsg        = { fg = c.blue },
    Question       = { fg = c.blue },
    WarningMsg     = { fg = c.warn },
    ErrorMsg       = { fg = c.error },
    Directory      = { fg = c.blue },
    Title          = { fg = c.purple,   bold = true },
    Todo           = { fg = c.bg,       bg = c.modifier, bold = true },
    NonText        = { fg = c.border },
    SpecialKey     = { fg = c.border },
    Whitespace     = { fg = c.border },
    Conceal        = { fg = c.fg_muted },
    SpellBad       = { undercurl = true, sp = c.error },
    SpellWarn      = { undercurl = true, sp = c.warn },
    SpellCap       = { undercurl = true, sp = c.info },
    SpellRare      = { undercurl = true, sp = c.hint },

    -- ── Diff ─────────────────────────────────────────────────────────────
    DiffAdd        = { fg = c.green,    bg = "#1a2e1a" },
    DiffChange     = { fg = c.blue,     bg = "#0d1e33" },
    DiffDelete     = { fg = c.red,      bg = "#2e0d1a" },
    DiffText       = { fg = c.modifier, bg = "#2e2300", bold = true },
    Added          = { fg = c.green },
    Changed        = { fg = c.blue },
    Removed        = { fg = c.red },

    -- ── Diagnostics ──────────────────────────────────────────────────────
    DiagnosticError            = { fg = c.error },
    DiagnosticWarn             = { fg = c.warn },
    DiagnosticInfo             = { fg = c.info },
    DiagnosticHint             = { fg = c.hint },
    DiagnosticOk               = { fg = c.green },
    DiagnosticUnderlineError   = { undercurl = true, sp = c.error },
    DiagnosticUnderlineWarn    = { undercurl = true, sp = c.warn },
    DiagnosticUnderlineInfo    = { undercurl = true, sp = c.info },
    DiagnosticUnderlineHint    = { undercurl = true, sp = c.hint },
    DiagnosticVirtualTextError = { fg = c.error,  bg = "#1e0d12", italic = true },
    DiagnosticVirtualTextWarn  = { fg = c.warn,   bg = "#1e160a", italic = true },
    DiagnosticVirtualTextInfo  = { fg = c.info,   bg = "#0d1622", italic = true },
    DiagnosticVirtualTextHint  = { fg = c.hint,   bg = "#13101e", italic = true },
    DiagnosticSignError        = { fg = c.error },
    DiagnosticSignWarn         = { fg = c.warn },
    DiagnosticSignInfo         = { fg = c.info },
    DiagnosticSignHint         = { fg = c.hint },

    -- ── Base syntax (legacy vim groups, treesitter fallback) ──────────────
    Comment        = { fg = c.comment,   italic = true },
    Constant       = { fg = c.blue },
    String         = { fg = c.string },
    Character      = { fg = c.string },
    Number         = { fg = c.purple },
    Float          = { fg = c.purple },
    Boolean        = { fg = c.keyword,   italic = true },
    Identifier     = { fg = c.gypsum },
    Function       = { fg = c.green },
    Statement      = { fg = c.keyword },
    Conditional    = { fg = c.keyword,   italic = true },
    Repeat         = { fg = c.keyword,   italic = true },
    Label          = { fg = c.keyword },
    Operator       = { fg = c.blue },
    Keyword        = { fg = c.keyword,   italic = true },
    Exception      = { fg = c.keyword },
    PreProc        = { fg = c.orange },
    Include        = { fg = c.keyword,   italic = true },
    Define         = { fg = c.orange },
    Macro          = { fg = c.blue },
    PreCondit      = { fg = c.orange },
    Type           = { fg = c.teal_type, italic = true },
    StorageClass   = { fg = c.modifier,  italic = true },
    Structure      = { fg = c.teal,      italic = true },
    Typedef        = { fg = c.teal_type, italic = true },
    Special        = { fg = c.blue },
    SpecialChar    = { fg = c.string },
    Tag            = { fg = c.keyword },
    Delimiter      = { fg = c.fg_dim },
    SpecialComment = { fg = c.comment,   bold = true },
    Debug          = { fg = c.red },
    Underlined     = { underline = true },
    Error          = { fg = c.error },

    -- ── Treesitter — identifiers ──────────────────────────────────────────
    ["@variable"]                   = { fg = c.gypsum },
    ["@variable.builtin"]           = { fg = c.keyword,    italic = true },
    ["@variable.parameter"]         = { fg = c.param },
    ["@variable.parameter.builtin"] = { fg = c.param,      italic = true },
    ["@variable.member"]            = { fg = "#b4f9f8" },

    -- ── Treesitter — constants ────────────────────────────────────────────
    ["@constant"]                   = { fg = c.blue },
    ["@constant.builtin"]           = { fg = c.blue,       italic = true },
    ["@constant.macro"]             = { fg = c.blue,       bold = true },

    -- ── Treesitter — strings ──────────────────────────────────────────────
    ["@string"]                     = { fg = c.string },
    ["@string.documentation"]       = { fg = c.string,     italic = true },
    ["@string.regexp"]              = { fg = c.orange },
    ["@string.escape"]              = { fg = c.red },
    ["@string.special"]             = { fg = c.string },
    ["@string.special.symbol"]      = { fg = c.purple },
    ["@string.special.url"]         = { fg = c.blue,       underline = true },

    -- ── Treesitter — literals ─────────────────────────────────────────────
    ["@character"]                  = { fg = c.string },
    ["@character.special"]          = { fg = c.red },
    ["@number"]                     = { fg = c.purple },
    ["@number.float"]               = { fg = c.purple },
    ["@boolean"]                    = { fg = c.keyword,    italic = true },

    -- ── Treesitter — functions ────────────────────────────────────────────
    ["@function"]                   = { fg = c.green },
    ["@function.builtin"]           = { fg = c.green_dim,  italic = true },
    ["@function.call"]              = { fg = c.green },
    ["@function.macro"]             = { fg = c.blue },
    ["@function.method"]            = { fg = c.green_dim },
    ["@function.method.call"]       = { fg = c.green_dim },
    ["@constructor"]                = { fg = c.teal },

    -- ── Treesitter — keywords ─────────────────────────────────────────────
    ["@keyword"]                    = { fg = c.keyword,    italic = true },
    ["@keyword.coroutine"]          = { fg = c.keyword,    italic = true },
    ["@keyword.function"]           = { fg = c.keyword,    italic = true },
    ["@keyword.operator"]           = { fg = c.keyword },
    ["@keyword.import"]             = { fg = c.keyword,    italic = true },
    ["@keyword.type"]               = { fg = c.teal_type,  italic = true },
    ["@keyword.modifier"]           = { fg = c.modifier,   italic = true },
    ["@keyword.repeat"]             = { fg = c.keyword,    italic = true },
    ["@keyword.return"]             = { fg = c.keyword,    italic = true },
    ["@keyword.debug"]              = { fg = c.red },
    ["@keyword.exception"]          = { fg = c.keyword },
    ["@keyword.conditional"]        = { fg = c.keyword,    italic = true },
    ["@keyword.conditional.ternary"]= { fg = c.blue },
    ["@keyword.directive"]          = { fg = c.orange },
    ["@keyword.directive.define"]   = { fg = c.orange },

    -- ── Treesitter — types ────────────────────────────────────────────────
    ["@type"]                       = { fg = c.teal_type,  italic = true },
    -- NOTE: type.builtin = gypsum for void/int/char
    -- To try coral-pink (same as uint32_t): swap "#e8e4dc" for c.type_stdlib
    ["@type.builtin"]               = { fg = "#e8e4dc",    italic = true },
    ["@type.definition"]            = { fg = c.teal_type },
    ["@type.qualifier"]             = { fg = c.modifier,   italic = true },

    -- ── Treesitter — attributes ───────────────────────────────────────────
    ["@attribute"]                  = { fg = c.blue },
    ["@attribute.builtin"]          = { fg = c.blue,       italic = true },
    ["@property"]                   = { fg = "#b4f9f8" },

    -- ── Treesitter — operators / punctuation ──────────────────────────────
    ["@operator"]                   = { fg = c.blue },
    ["@punctuation.delimiter"]      = { fg = c.fg_dim },
    ["@punctuation.bracket"]        = { fg = c.fg_dim },
    ["@punctuation.special"]        = { fg = c.blue },

    -- ── Treesitter — comments ─────────────────────────────────────────────
    ["@comment"]                    = { fg = c.comment,    italic = true },
    ["@comment.documentation"]      = { fg = c.comment,    italic = true },
    ["@comment.error"]              = { fg = c.error,      bold = true },
    ["@comment.warning"]            = { fg = c.warn,       bold = true },
    ["@comment.todo"]               = { fg = c.modifier,   bold = true },
    ["@comment.note"]               = { fg = c.info,       bold = true },

    -- ── Treesitter — markup ───────────────────────────────────────────────
    ["@markup.strong"]              = { bold = true },
    ["@markup.italic"]              = { italic = true },
    ["@markup.strikethrough"]       = { strikethrough = true },
    ["@markup.underline"]           = { underline = true },
    ["@markup.heading"]             = { fg = c.keyword,    bold = true },
    ["@markup.heading.1"]           = { fg = c.red,        bold = true },
    ["@markup.heading.2"]           = { fg = c.keyword,    bold = true },
    ["@markup.heading.3"]           = { fg = c.modifier,   bold = true },
    ["@markup.heading.4"]           = { fg = c.green,      bold = true },
    ["@markup.heading.5"]           = { fg = c.blue,       bold = true },
    ["@markup.heading.6"]           = { fg = c.purple,     bold = true },
    ["@markup.quote"]               = { fg = c.fg_dim,     italic = true },
    ["@markup.math"]                = { fg = c.blue },
    ["@markup.link"]                = { fg = c.blue,       underline = true },
    ["@markup.link.label"]          = { fg = c.purple },
    ["@markup.link.url"]            = { fg = c.blue,       underline = true },
    ["@markup.raw"]                 = { fg = c.string },
    ["@markup.raw.block"]           = { fg = c.string },
    ["@markup.list"]                = { fg = c.keyword },
    ["@markup.list.checked"]        = { fg = c.green },
    ["@markup.list.unchecked"]      = { fg = c.fg_dim },

    -- ── Treesitter — tags (HTML/JSX) ──────────────────────────────────────
    ["@tag"]                        = { fg = c.keyword },
    ["@tag.builtin"]                = { fg = c.keyword,    italic = true },
    ["@tag.attribute"]              = { fg = c.teal_type,  italic = true },
    ["@tag.delimiter"]              = { fg = c.fg_dim },

    -- ── Treesitter — misc ─────────────────────────────────────────────────
    ["@none"]                       = {},
    ["@conceal"]                    = { fg = c.fg_muted },
    ["@error"]                      = { fg = c.error },

    -- ── LSP semantic tokens ───────────────────────────────────────────────
    ["@lsp.type.class"]             = { fg = c.teal,       italic = true },
    ["@lsp.type.comment"]           = { fg = c.comment,    italic = true },
    ["@lsp.type.decorator"]         = { fg = c.blue },
    ["@lsp.type.enum"]              = { fg = c.teal_type },
    -- NOTE: enumMember = blue (same as macros — both are named constant values)
    -- To distinguish: swap c.blue for c.purple below
    ["@lsp.type.enumMember"]        = { fg = c.blue },
    ["@lsp.type.event"]             = { fg = c.teal_type },
    ["@lsp.type.function"]          = { fg = c.green },
    ["@lsp.type.interface"]         = { fg = c.teal,       italic = true },
    ["@lsp.type.keyword"]           = { fg = c.keyword,    italic = true },
    ["@lsp.type.macro"]             = { fg = c.blue },
    ["@lsp.type.method"]            = { fg = c.green_dim },
    ["@lsp.type.modifier"]          = { fg = c.modifier,   italic = true },
    ["@lsp.type.namespace"]         = { fg = c.fg_dim },
    ["@lsp.type.number"]            = { fg = c.purple },
    ["@lsp.type.operator"]          = { fg = c.blue },
    ["@lsp.type.parameter"]         = { fg = c.param },
    ["@lsp.type.property"]          = { fg = "#b4f9f8" },
    ["@lsp.type.regexp"]            = { fg = c.orange },
    ["@lsp.type.string"]            = { fg = c.string },
    ["@lsp.type.struct"]            = { fg = c.teal,       italic = true },
    -- NOTE: @lsp.type.type = teal_type for typedef handles (Button_TypeDef etc.)
    -- To compare with teal: swap c.teal_type for c.teal below
    ["@lsp.type.type"]              = { fg = c.teal_type,  italic = true },
    ["@lsp.type.typeParameter"]     = { fg = c.param,      italic = true },
    ["@lsp.type.variable"]          = { fg = c.gypsum },

    -- LSP modifier combinations
    ["@lsp.typemod.function.defaultLibrary"]  = { fg = c.green_dim,   italic = true },
    ["@lsp.typemod.variable.defaultLibrary"]  = { fg = c.keyword,     italic = true },
    ["@lsp.typemod.variable.globalScope"]     = { fg = c.gypsum },
    ["@lsp.typemod.variable.readonly"]        = { fg = c.gypsum,      italic = true },
    ["@lsp.typemod.variable.static"]          = { fg = c.gypsum },
    ["@lsp.typemod.variable.fileScope"]       = { fg = c.gypsum },
    ["@lsp.typemod.property.readonly"]        = { fg = "#b4f9f8",     italic = true },
    ["@lsp.typemod.property.classScope"]      = { fg = "#b4f9f8" },
    ["@lsp.typemod.keyword.documentation"]    = { fg = c.keyword,     bold = true },
    ["@lsp.typemod.class.defaultLibrary"]     = { fg = c.teal,        italic = true },
    -- NOTE: type_stdlib = coral-pink for stdlib typedefs (uint32_t, int32_t)
    -- To compare with teal_type: swap c.type_stdlib for c.teal_type below
    ["@lsp.typemod.type.defaultLibrary"]      = { fg = c.type_stdlib, italic = true },

    -- ── Gitsigns ─────────────────────────────────────────────────────────
    GitSignsAdd              = { fg = c.green },
    GitSignsChange           = { fg = c.blue },
    GitSignsDelete           = { fg = c.red },
    GitSignsAddNr            = { fg = c.green },
    GitSignsChangeNr         = { fg = c.blue },
    GitSignsDeleteNr         = { fg = c.red },
    GitSignsAddLn            = { bg = "#1a2e1a" },
    GitSignsChangeLn         = { bg = "#0d1e33" },

    -- ── Telescope ─────────────────────────────────────────────────────────
    TelescopeNormal          = { fg = c.fg,        bg = c.bg_float },
    TelescopeBorder          = { fg = c.border_hl, bg = c.bg_float },
    TelescopePromptNormal    = { fg = c.fg,        bg = c.bg_subtle2 },
    TelescopePromptBorder    = { fg = c.bg_subtle2, bg = c.bg_subtle2 },
    TelescopePromptPrefix    = { fg = c.keyword },
    TelescopePromptTitle     = { fg = c.bg,        bg = c.keyword },
    TelescopePreviewTitle    = { fg = c.bg,        bg = c.green },
    TelescopeResultsTitle    = { fg = c.bg,        bg = c.blue },
    TelescopeMatching        = { fg = c.modifier,  bold = true },
    TelescopeSelection       = { bg = c.bg_sel },
    TelescopeSelectionCaret  = { fg = c.keyword,   bg = c.bg_sel },

    -- ── nvim-cmp ──────────────────────────────────────────────────────────
    CmpItemAbbr              = { fg = c.fg },
    CmpItemAbbrDeprecated    = { fg = c.fg_muted,  strikethrough = true },
    CmpItemAbbrMatch         = { fg = c.modifier,  bold = true },
    CmpItemAbbrMatchFuzzy    = { fg = c.modifier },
    CmpItemKind              = { fg = c.blue },
    CmpItemMenu              = { fg = c.fg_dim,    italic = true },
    CmpItemKindFunction      = { fg = c.green },
    CmpItemKindMethod        = { fg = c.green_dim },
    CmpItemKindConstructor   = { fg = c.teal },
    CmpItemKindClass         = { fg = c.teal },
    CmpItemKindInterface     = { fg = c.teal },
    CmpItemKindStruct        = { fg = c.teal },
    CmpItemKindVariable      = { fg = c.gypsum },
    CmpItemKindField         = { fg = "#b4f9f8" },
    CmpItemKindProperty      = { fg = "#b4f9f8" },
    CmpItemKindKeyword       = { fg = c.keyword },
    CmpItemKindText          = { fg = c.fg_dim },
    CmpItemKindSnippet       = { fg = c.modifier },
    CmpItemKindModule        = { fg = c.teal_type },
    CmpItemKindEnum          = { fg = c.teal_type },
    CmpItemKindEnumMember    = { fg = c.blue },
    CmpItemKindConstant      = { fg = c.blue },
    CmpItemKindTypeParameter = { fg = c.param },
    CmpItemKindOperator      = { fg = c.blue },
    CmpItemKindUnit          = { fg = c.purple },
    CmpItemKindValue         = { fg = c.purple },
    CmpItemKindEvent         = { fg = c.teal_type },
    CmpItemKindColor         = { fg = c.modifier },
    CmpItemKindReference     = { fg = c.blue },
    CmpItemKindFolder        = { fg = c.modifier },
    CmpItemKindFile          = { fg = c.modifier },

    -- ── Which-key ─────────────────────────────────────────────────────────
    WhichKey          = { fg = c.keyword },
    WhichKeyGroup     = { fg = c.blue },
    WhichKeyDesc      = { fg = c.fg },
    WhichKeySeparator = { fg = c.fg_muted },
    WhichKeyValue     = { fg = c.fg_dim },
    WhichKeyBorder    = { fg = c.border_hl },
    WhichKeyNormal    = { bg = c.bg_float },

    -- ── Indent blankline ──────────────────────────────────────────────────
    IblIndent                     = { fg = c.border },
    IblScope                      = { fg = c.purple_dim },
    IndentBlanklineChar           = { fg = c.border },
    IndentBlanklineContextChar    = { fg = c.purple_dim },

    -- ── nvim-tree ─────────────────────────────────────────────────────────
    NvimTreeNormal           = { fg = c.fg,        bg = c.bg_float },
    NvimTreeRootFolder       = { fg = c.keyword,   bold = true },
    NvimTreeFolderName       = { fg = c.blue },
    NvimTreeOpenedFolderName = { fg = c.blue,      bold = true },
    NvimTreeEmptyFolderName  = { fg = c.fg_dim },
    NvimTreeFolderIcon       = { fg = c.blue },
    NvimTreeFileIcon         = { fg = c.fg_dim },
    NvimTreeFileName         = { fg = c.fg },
    NvimTreeExecFile         = { fg = c.green,     bold = true },
    NvimTreeGitDirty         = { fg = c.orange },
    NvimTreeGitNew           = { fg = c.green },
    NvimTreeGitDeleted       = { fg = c.red },
    NvimTreeGitIgnored       = { fg = c.fg_muted },
    NvimTreeSymlink          = { fg = c.cyan },
    NvimTreeSpecialFile      = { fg = c.purple },
    NvimTreeIndentMarker     = { fg = c.border },
    NvimTreeWinSeparator     = { fg = c.border },

    -- ── Notify ────────────────────────────────────────────────────────────
    NotifyERRORBorder = { fg = c.error },
    NotifyWARNBorder  = { fg = c.warn },
    NotifyINFOBorder  = { fg = c.info },
    NotifyDEBUGBorder = { fg = c.fg_muted },
    NotifyTRACEBorder = { fg = c.purple },
    NotifyERRORIcon   = { fg = c.error },
    NotifyWARNIcon    = { fg = c.warn },
    NotifyINFOIcon    = { fg = c.info },
    NotifyDEBUGIcon   = { fg = c.fg_muted },
    NotifyTRACEIcon   = { fg = c.purple },
    NotifyERRORTitle  = { fg = c.error,    bold = true },
    NotifyWARNTitle   = { fg = c.warn,     bold = true },
    NotifyINFOTitle   = { fg = c.info,     bold = true },
    NotifyDEBUGTitle  = { fg = c.fg_muted },
    NotifyTRACETitle  = { fg = c.purple },
  }

  for group, opts in pairs(highlights) do
    vim.api.nvim_set_hl(0, group, opts)
  end
end

return M
